name: Wakatime Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.PAT  }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_EDITORS: "False" # VS CODE
          SHOW_OS: "True" # I only use Windows and Arch
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_UPDATED_DATE: "False"
          COMMIT_MESSAGE: "Automated Coding Activity Update :alien:"